apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: default
  labels:
    app: envoy-proxy
    component: config
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901

    static_resources:
      listeners:
      - name: websocket_listener
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              scheme_header_transformation:
                scheme_to_overwrite: http
              stat_prefix: websocket_proxy
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                  log_format:
                    text_format: |
                      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
              route_config:
                name: local_route
                virtual_hosts:
                - name: websocket_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                      headers:
                      - name: "upgrade"
                        string_match:
                          exact: "websocket"
                    route:
                      cluster: websocket_cluster
                      timeout: 0s
                      upgrade_configs:
                      - upgrade_type: "websocket"
                  - match:
                      prefix: "/"
                    route:
                      cluster: websocket_cluster
              http_filters:
              # Disabled Lua filter for now due to configuration issues
              # - name: envoy.filters.http.lua
              #   typed_config:
              #     "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              #     inline_code: |
              #       function envoy_on_request(request_handle)
              #         -- Basic rate limiting without Redis for now
              #         request_handle:headers():add("x-envoy-processed", "true")
              #       end
              - name: envoy.filters.http.fault
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
                  abort:
                    percentage:
                      numerator: 1
                      denominator: MILLION
                    http_status: 503
                  response_rate_limit:
                    fixed_limit:
                      limit_kbps: 1000
                  headers:
                  - append: false
                    header:
                      key: x-fallback-rate-limited
                      value: 'true'
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      - name: websocket_cluster
        connect_timeout: 30s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        dns_lookup_family: V4_ONLY
        circuit_breakers:
          thresholds:
          - priority: DEFAULT
            max_connections: 8        # 4 backend pods * 2 connections per pod
            max_pending_requests: 10
            max_requests: 20
            max_retries: 3
        health_checks:
        - timeout: 5s
          interval: 10s
          interval_jitter: 1s
          unhealthy_threshold: 3
          healthy_threshold: 2
          tcp_health_check: {}
        load_assignment:
          cluster_name: websocket_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: envoy-poc-app-server-service.default.svc.cluster.local
                    port_value: 8080
        # Connection pool settings for WebSocket connections
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http_protocol_options:
                accept_http_10: true
            upstream_http_protocol_options:
              auto_sni: true

      - name: redis_http_proxy
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: redis_http_proxy
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: redis-http-proxy.default.svc.cluster.local
                    port_value: 8080

---
# Note: The envoy-lua-scripts ConfigMap will be created by the update-lua-configmap.sh script
# from the standalone redis-connection-tracker.lua file

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: default
  labels:
    app: envoy-proxy
    component: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
        component: proxy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.31-latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9901
          name: admin
        env:
        - name: ENVOY_LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
          readOnly: true
        - name: lua-scripts
          mountPath: /etc/envoy/lua
          readOnly: true
        command:
        - /usr/local/bin/envoy
        args:
        - --config-path
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - envoy-proxy
        - --service-node
        - envoy-proxy
        - --log-level
        - info
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 9901
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 9901
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
      - name: lua-scripts
        configMap:
          name: envoy-lua-scripts
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-service
  namespace: default
  labels:
    app: envoy-proxy
    component: service
spec:
  selector:
    app: envoy-proxy
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 9901
    targetPort: 9901
    name: admin
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-nodeport
  namespace: default
  labels:
    app: envoy-proxy
    component: nodeport
spec:
  selector:
    app: envoy-proxy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  type: NodePort
