apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: default
  labels:
    app: redis-service
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        command:
        - redis-server
        args:
        - --save
        - "60"
        - "1"
        - --loglevel
        - warning
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    app: redis-service
spec:
  selector:
    app: redis-service
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
