apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-poc-client-app
  namespace: default
  labels:
    app: envoy-poc-client-app
    component: websocket-client
    version: 1.0.0
spec:
  replicas: 10
  selector:
    matchLabels:
      app: envoy-poc-client-app
  template:
    metadata:
      labels:
        app: envoy-poc-client-app
        component: websocket-client
        version: 1.0.0
    spec:
      containers:
      - name: websocket-client
        image: IMAGE_REGISTRY_PLACEHOLDER
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        env:
        - name: ENVOY_ENDPOINT
          value: "ws://abd77a2291c1d4425929acfeb07cd281-12129355f635ff43.elb.us-west-2.amazonaws.com:80"
        - name: CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HEALTH_PORT
          value: "8081"
        - name: MAX_CONNECTIONS
          value: "5"
        - name: CONNECTION_INTERVAL
          value: "10"
        - name: MESSAGE_INTERVAL_MIN
          value: "10"
        - name: MESSAGE_INTERVAL_MAX
          value: "20"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-poc-client-service
  namespace: default
  labels:
    app: envoy-poc-client-app
    component: websocket-client
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: health
  selector:
    app: envoy-poc-client-app
